name: Test Cluster-CI Runner

on:
  push:
    branches:
      - main

jobs:
  test_pipeline:
    runs-on: self-hosted
    steps:
      - name: Trigger Orchestrator Script
        run: /home/lopilo/code/cluster-ci/src/runner/run_research_pipeline.sh ${{ github.repository }} ${{ github.head_ref || github.ref_name }} ${{ secrets.GITHUB_TOKEN }}
